// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// "dotenv/config" domyślnie czyta tylko .env — projekt trzyma sekrety w .env.local
// (konwencja Next.js), więc trzeba je załadować jawnie.
loadEnv({ path: ".env.local" });
loadEnv();

// CLI (migrate/seed/studio) łączy się bezpośrednio, z pominięciem poolera —
// runtime aplikacji (lib/prisma.ts) używa osobno DATABASE_URL przez HTTP driver Neona.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
